//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string EmployeeId { get; set; }
        public System.DateTime DateWork { get; set; }
        public Nullable<System.DateTime> TimeCheckIn { get; set; }
        public Nullable<System.DateTime> TimeCheckOut { get; set; }
        public double HourWork { get; set; }
    }
}
