//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> StatusUser { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public string UserLastUpdate { get; set; }
    }
}
